### ISSUE TITLE
some questions about the Efficient Frame Pruning

### ISSUE THREAD

**Issue by Shine-Ray** [jinlab-imvr/Surgical-SAM-2#2]
Wonderful Work!
I have some questions about the Efficient Frame Pruning part.

It is described in section 3.2 of the paper as follows: for each frame ft passed to the memory bank, cosine similarity is computed between ft and the past n frames, and then the mechanism identifies the m most similar frames from these n frames. These m frames are pruned and the remaining (n-m) frames plus frame ft are stored in the memory bank. However, in the code Surgical-SAM-2/sam2/modeling/sam2_base.py, line:581, the function of this program is to remove the feature with the lowest cosine similarity to the latest frame from the memory bank.

Can you tell me whether frames with high cosine similarity to the latest frame or frames with low cosine similarity should be removed from the memory bank? Thank you!

**Comment by HeverLaw** [comment]
Thank you for your question. During the code publication, we inadvertently included an incorrect code comment.
The correct comment should be:
"remove num_remove memory frames most similar to the last frame"
This is equivalent to:
"remove the memory with the highest cosine similarity to the last frame."
This corrected comment accurately reflects the original runnable code and the description in our paper.
"""
cos_sim = list(sorted(cos_sim.items(), key=lambda x: x[1], reverse=True))  # the ranking is from large to small
delete_index = sorted([cos_sim[i][0] for i in range(num_remove)], reverse=True)  # delete 'num_remove' frames with larger cos_sim 
"""
We also modify the corresponding code comment in the code to avoid misunderstanding.
